// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceResearchManagementSystem.Data;

#nullable disable

namespace SpaceResearchManagementSystem.Migrations
{
    [DbContext(typeof(SpaceResearchContext))]
    [Migration("20241206170225_thgv")]
    partial class thgv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.CostManagement", b =>
                {
                    b.Property<int>("CostManagementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostManagementId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.HasKey("CostManagementId");

                    b.HasIndex("MissionId");

                    b.ToTable("CostManagements");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.EnvironmentalData", b =>
                {
                    b.Property<int>("EnvironmentalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnvironmentalDataId"));

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssessmentDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImpactType")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.HasKey("EnvironmentalDataId");

                    b.HasIndex("MissionId");

                    b.ToTable("EnvironmentalDatas");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int?>("AssignedMissionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentId");

                    b.HasIndex("AssignedMissionId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<string>("AssignedTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MissionId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.MissionPerformance", b =>
                {
                    b.Property<int>("MissionPerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionPerformanceId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("PerformanceMetrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("MissionPerformanceId");

                    b.HasIndex("MissionId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("MissionPerformances");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.ProjectPlan", b =>
                {
                    b.Property<int>("ProjectPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectPlanId"));

                    b.Property<int?>("AssignedEngineerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectPlanId");

                    b.HasIndex("AssignedEngineerId");

                    b.HasIndex("MissionId");

                    b.ToTable("ProjectPlans");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MissionId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.SafetyLog", b =>
                {
                    b.Property<int>("SafetyLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SafetyLogId"));

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("SafetyLogId");

                    b.HasIndex("MissionId");

                    b.ToTable("SafetyLogs");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.ScientificData", b =>
                {
                    b.Property<int>("ScientificDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScientificDataId"));

                    b.Property<DateTime>("CollectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("ResearcherId")
                        .HasColumnType("int");

                    b.HasKey("ScientificDataId");

                    b.HasIndex("MissionId");

                    b.HasIndex("ResearcherId");

                    b.ToTable("ScientificDatas");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.CostManagement", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", "Mission")
                        .WithMany("CostManagements")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.EnvironmentalData", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", "Mission")
                        .WithMany("EnvironmentalDatas")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Equipment", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", "AssignedMission")
                        .WithMany("Equipments")
                        .HasForeignKey("AssignedMissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedMission");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Mission", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.User", "Director")
                        .WithMany("DirectedMissions")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.MissionPerformance", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", "Mission")
                        .WithMany("MissionPerformances")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceResearchManagementSystem.Models.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Notification", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.ProjectPlan", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.User", "AssignedEngineer")
                        .WithMany()
                        .HasForeignKey("AssignedEngineerId");

                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", "Mission")
                        .WithMany("ProjectPlans")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedEngineer");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Report", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", null)
                        .WithMany("Reports")
                        .HasForeignKey("MissionId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.SafetyLog", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", "Mission")
                        .WithMany("SafetyLogs")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.ScientificData", b =>
                {
                    b.HasOne("SpaceResearchManagementSystem.Models.Mission", "Mission")
                        .WithMany("ScientificDatas")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceResearchManagementSystem.Models.User", "Researcher")
                        .WithMany()
                        .HasForeignKey("ResearcherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Researcher");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.Mission", b =>
                {
                    b.Navigation("CostManagements");

                    b.Navigation("EnvironmentalDatas");

                    b.Navigation("Equipments");

                    b.Navigation("MissionPerformances");

                    b.Navigation("ProjectPlans");

                    b.Navigation("Reports");

                    b.Navigation("SafetyLogs");

                    b.Navigation("ScientificDatas");
                });

            modelBuilder.Entity("SpaceResearchManagementSystem.Models.User", b =>
                {
                    b.Navigation("DirectedMissions");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
